# Generated by Django 2.0.7 on 2018-08-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Cotton Cushions', 'Cotton Cushions'), ('Polyester Cushions', 'Polyester Cushions')], max_length=250, unique=True),
        ),
    ]
