# Generated by Django 2.0.7 on 2018-08-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='buyer',
        ),
    ]
